import os
import pandas as pd
from algotrader.logger import get_logger
from algotrader.features import build_bracket_targets, merge_financials

logger = get_logger(__name__)


def setup_parser(subparsers):
    """Sets up the argparse subparser for the 'train' command."""
    parser = subparsers.add_parser(
        "train", help="Train the ML model simulating bracket orders on historical data"
    )

    parser.add_argument(
        "--dataset-dir",
        type=str,
        default="data/raw/alpaca",  # Fixed default to point to the correct ingest folder
        help="Directory containing the local dataset (CSV files) generated by the ingest command",
    )
    parser.add_argument(
        "--processed-dir",
        type=str,
        default="data/processed",
        help="Directory to save the merged, processed CSVs ready for model training",
    )
    parser.add_argument(
        "--model-name",
        type=str,
        default="model.pkl",
        help="Name of the model file to save after training",
    )
    parser.add_argument(
        "--horizon",
        type=int,
        default=63,
        help="Lookahead horizon in trading days for target creation (e.g., 21 for 1 month, 63 for 3 months)",
    )
    parser.add_argument(
        "--take-profit",
        type=float,
        default=0.10,
        help="Take profit percentage for the simulated bracket order (e.g., 0.10 for +10%)",
    )
    parser.add_argument(
        "--stop-loss",
        type=float,
        default=-0.05,
        help="Stop loss percentage for the simulated bracket order (e.g., -0.05 for -5%)",
    )
    parser.add_argument(
        "--min-net-income-growth",
        type=float,
        default=None,
        help="Only simulate trades when net_income_pct_change is over this percentage (e.g., 0.05 for 5%)"
    )

    parser.set_defaults(func=handle_train)


def handle_train(args):
    """Handler for the 'train' command."""
    logger.info(
        f"Starting training process using dataset directory: {args.dataset_dir}"
    )
    logger.info(
        f"Bracket Order Settings -> Horizon: {args.horizon} days | TP: {args.take_profit:.1%} | SL: {args.stop_loss:.1%}"
    )
    
    if args.min_net_income_growth is not None:
        logger.info(f"Trade Filter -> Net Income Pct Change > {args.min_net_income_growth:.1%}")

    if not os.path.exists(args.dataset_dir):
        logger.error(
            f"Dataset directory not found: {args.dataset_dir}. Please run the 'ingest' command first."
        )
        return

    csv_files = [f for f in os.listdir(args.dataset_dir) if f.endswith(".csv")]
    if not csv_files:
        logger.error(
            f"No CSV files found in {args.dataset_dir}. Please run the 'ingest' command first."
        )
        return

    logger.info(f"Found {len(csv_files)} historical data files. Loading dataset...")

    horizon = args.horizon
    take_profit = args.take_profit
    stop_loss = args.stop_loss

    # Deduce the polygon directory from the alpaca directory
    polygon_dir = os.path.join(os.path.dirname(args.dataset_dir), "polygon")

    # Create the processed directory
    os.makedirs(args.processed_dir, exist_ok=True)
    logger.info(f"Processed datasets will be saved to: {args.processed_dir}")

    # Load local data
    dataframes = {}
    for file_name in csv_files:
        symbol = file_name.replace(".csv", "")
        file_path = os.path.join(args.dataset_dir, file_name)
        
        # Alpaca data saves with a MultiIndex (symbol, timestamp) which becomes columns in CSV.
        # We explicitly parse the 'timestamp' column and strip the timezone 
        # to match the tz-naive SEC filing dates from Polygon for the point-in-time merge.
        df = pd.read_csv(file_path)
        
        if "timestamp" in df.columns:
            df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True).dt.tz_localize(None)
            df.set_index("timestamp", inplace=True)
        else:
            logger.warning(f"Could not find 'timestamp' column in {file_name}. Skipping.")
            continue

        # 1. Merge Financial Features (prevents look-ahead bias)
        df = merge_financials(df, symbol, polygon_dir)

        # 2. Build Targets simulating a bracket order
        df = build_bracket_targets(
            df, 
            horizon=horizon, 
            take_profit=take_profit, 
            stop_loss=stop_loss
        )

        # Drop the last 'horizon' rows because we don't know their future outcomes yet
        df.dropna(subset=[f"bracket_outcome_{horizon}d"], inplace=True)
        
        # 3. Apply the Fundamental Filter
        # Excludes any days/simulated trades where the required net income growth wasn't met
        if args.min_net_income_growth is not None:
            if "net_income_pct_change" in df.columns:
                df = df[df["net_income_pct_change"] > args.min_net_income_growth]
            else:
                # If no financials could be loaded for this stock, it fails the strict filter
                df = df.iloc[0:0]

        if not df.empty:
            dataframes[symbol] = df
            
            # Save the processed and combined dataframe
            processed_file_path = os.path.join(args.processed_dir, f"{symbol}.csv")
            df.to_csv(processed_file_path)

    if not dataframes:
        logger.error("No valid dataset remaining after bracket generation and fundamental filtering.")
        return

    logger.info(
        f"Successfully loaded and processed targets for {len(dataframes)} symbols."
    )

    # Show a quick summary of the target distributions to ensure it worked
    all_data = pd.concat(dataframes.values())
    
    outcome_col = f"bracket_outcome_{horizon}d"
    total_samples = len(all_data)
    tp_hits = (all_data[outcome_col] == 1).sum()
    sl_hits = (all_data[outcome_col] == -1).sum()
    expired = (all_data[outcome_col] == 0).sum()
    avg_return = all_data[f"bracket_return_{horizon}d"].mean()
    avg_duration = all_data[f"bracket_duration_{horizon}d"].mean()

    logger.info(f"=== {horizon}-Day Bracket Order Outcomes ===")
    logger.info(f"Total historical samples (trades taken):  {total_samples:,}")
    logger.info(f"Hit Take Profit (+{take_profit:.1%}): {tp_hits/total_samples:.2%} ({tp_hits:,} samples)")
    logger.info(f"Hit Stop Loss   ({stop_loss:.1%}): {sl_hits/total_samples:.2%} ({sl_hits:,} samples)")
    logger.info(f"Expired (Neither hit):     {expired/total_samples:.2%} ({expired:,} samples)")
    logger.info(f"Average Bracket Return:    {avg_return:.2%}")
    logger.info(f"Average Trade Duration:    {avg_duration:.1f} days")

    # Ensure the models directory exists
    os.makedirs("models", exist_ok=True)
    model_path = os.path.join("models", args.model_name)

    # TODO: Implement training logic (e.g., using scikit-learn or xgboost on all_data)
    # logger.info(f"Training complete. Model would be saved to '{model_path}'.")
