import os
import pandas as pd
from algotrader.logger import get_logger
from algotrader.features import build_targets

logger = get_logger(__name__)


def setup_parser(subparsers):
    """Sets up the argparse subparser for the 'train' command."""
    parser = subparsers.add_parser(
        "train", help="Train the ML model on local historical dataset"
    )

    parser.add_argument(
        "--dataset-dir",
        type=str,
        default="data/raw/alpaca",  # Fixed default to point to the correct ingest folder
        help="Directory containing the local dataset (CSV files) generated by the ingest command",
    )
    parser.add_argument(
        "--model-name",
        type=str,
        default="model.pkl",
        help="Name of the model file to save after training",
    )

    parser.set_defaults(func=handle_train)


def handle_train(args):
    """Handler for the 'train' command."""
    logger.info(
        f"Starting training process using dataset directory: {args.dataset_dir}"
    )

    if not os.path.exists(args.dataset_dir):
        logger.error(
            f"Dataset directory not found: {args.dataset_dir}. Please run the 'ingest' command first."
        )
        return

    csv_files = [f for f in os.listdir(args.dataset_dir) if f.endswith(".csv")]
    if not csv_files:
        logger.error(
            f"No CSV files found in {args.dataset_dir}. Please run the 'ingest' command first."
        )
        return

    logger.info(f"Found {len(csv_files)} historical data files. Loading dataset...")

    # Load local data
    dataframes = {}
    for file_name in csv_files:
        symbol = file_name.replace(".csv", "")
        file_path = os.path.join(args.dataset_dir, file_name)
        df = pd.read_csv(file_path, index_col=0, parse_dates=True)

        # Build Targets (21 trading days = ~1 month)
        df = build_targets(df, horizons=[21], thresholds=[0.05, 0.10, 0.20])

        # Drop the last 21 rows because we don't know their future outcomes yet
        df.dropna(subset=["return_future_21d"], inplace=True)

        dataframes[symbol] = df

    logger.info(
        f"Successfully loaded and processed targets for {len(dataframes)} symbols."
    )

    # Show a quick summary of the target distributions to ensure it worked
    all_data = pd.concat(dataframes.values())
    logger.info("=== 1-Month Target Distributions ===")
    logger.info(f"Total historical samples: {len(all_data):,}")
    logger.info(f"Hit Target 5%:  {all_data['target_21d_5pct'].mean():.2%}")
    logger.info(f"Hit Target 10%: {all_data['target_21d_10pct'].mean():.2%}")
    logger.info(f"Hit Target 20%: {all_data['target_21d_20pct'].mean():.2%}")

    # Ensure the models directory exists
    os.makedirs("models", exist_ok=True)
    model_path = os.path.join("models", args.model_name)

    # TODO: Implement training logic (e.g., using scikit-learn or xgboost on all_data)
    # logger.info(f"Training complete. Model would be saved to '{model_path}'.")
